name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies for admin
        run: |
          npm install
          npm run build
        working-directory: .\admin

      - name: Install dependencies for user
        run: |
          npm install
          npm run build
        working-directory: .\user

      - name: Install dependencies for server
        run: |
          npm install
        working-directory: .\server

  deploy:
    name: Deploy
    needs: build
    runs-on: [self-hosted, windows]

    steps:
      - name: Deploy Admin
        run: npm run dev
        working-directory: .\admin

      - name: Deploy User
        run: npm run dev
        working-directory: .\user

      - name: Deploy Server
        run: node index.js
        working-directory: .\server
